<a href="https://colab.research.google.com/github/Ravi-Poddar26/Feature-Engineering/blob/master/Encoding_data2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#One Hot Encoding

This is user when many different types of data present but not camparision of each other.

**Note :** In one hot encoding if n different type of object are present then n-1 columns will be created because first column will be rebunted (because for one object all number is zero ) this is called dummy variable trap.

If there are so many differnt-different types of object are present than we use most frequent object and for all other we merge the data and name them other.

In [ ]:
import zipfile
with zipfile.ZipFile('/content/archive (1).zip') as data:
  data.extractall()

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/content/drive/MyDrive/pre-owned cars.csv')

In [3]:
data

brand                                     model transmission  \
0     Mahindra              Thar LX D 4WD MT CONVERTIBLE       Manual   
1      Hyundai                         Verna 1.6 VTVT SX       Manual   
2         Tata  Harrier XT PLUS 2.0L KRYOTEC DARK EDITON       Manual   
3        Honda                     City 1.5L I-VTE V CVT    Automatic   
4         Ford             Ecosport TITANIUM 1.5L DIESEL       Manual   
...        ...                                       ...          ...   
2801      Ford           Ecosport TREND + 1.5L PETROL AT    Automatic   
2802     Honda                        Jazz 1.2L I-VTEC V       Manual   
2803   Hyundai                       Elite i20 MAGNA 1.2       Manual   
2804    Maruti                   Baleno DELTA PETROL 1.2       Manual   
2805       NaN                                       NaN          NaN   

      make_year    reg_year fuel_type  engine_capacity(CC)  km_driven  \
0        2020.0  01-01-2021    Diesel               2184.0    11003.0   
1        2018.0  01-07-2018    Petrol               1591.0    66936.0   
2        2022.0  01-08-2022    Diesel               1956.0    27990.0   
3        2023.0  01-04-2023    Petrol               1498.0     5061.0   
4        2021.0  01-07-2021    Diesel               1498.0    23480.0   
...         ...         ...       ...                  ...        ...   
2801     2018.0         NaN    Petrol               1497.0    46982.0   
2802     2015.0         NaN    Petrol               1199.0    38706.0   
2803     2016.0         NaN    Petrol               1197.0    31405.0   
2804     2017.0         NaN    Petrol               1197.0    47676.0   
2805        NaN         NaN       NaN                  NaN        NaN   

      ownership       price  overall_cost has_insurance spare_key reg_number  \
0     1st owner     1231000       23431.0          True        No       HR26   
1     1st owner      786000       15359.0          True        No       DL7C   
2     1st owner     1489000       28349.0          True        No       HR29   
3     1st owner     1227000       23355.0          True       Yes       DL4C   
4     1st owner      887000       16883.0          True        No       UP14   
...         ...         ...           ...           ...       ...        ...   
2801  1st owner      661000       12920.0          True       Yes       MH03   
2802  2nd owner      412000        8057.0          True       Yes       MH01   
2803  1st owner      496000        9704.0          True       Yes       MH03   
2804  1st owner      509000        9959.0          True       Yes       MH04   
2805        NaN  1883558000           NaN           NaN       NaN        NaN   

                                                  title  
0            2020 Mahindra Thar LX D 4WD MT CONVERTIBLE  
1                        2018 Hyundai Verna 1.6 VTVT SX  
2     2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...  
3                      2023 Honda City 1.5L I-VTE V CVT  
4               2021 Ford Ecosport TITANIUM 1.5L DIESEL  
...                                                 ...  
2801          2018 Ford Ecosport TREND + 1.5L PETROL AT  
2802                      2015 Honda Jazz 1.2L I-VTEC V  
2803                   2016 Hyundai Elite i20 MAGNA 1.2  
2804                2017 Maruti Baleno DELTA PETROL 1.2  
2805                                                NaN  

[2806 rows x 15 columns]

In [4]:
data = data.drop(columns=['model','make_year','reg_year','engine_capacity(CC)','has_insurance','spare_key','reg_number','title','overall_cost'])

In [5]:
data

brand transmission fuel_type  km_driven  ownership       price
0     Mahindra       Manual    Diesel    11003.0  1st owner     1231000
1      Hyundai       Manual    Petrol    66936.0  1st owner      786000
2         Tata       Manual    Diesel    27990.0  1st owner     1489000
3        Honda    Automatic    Petrol     5061.0  1st owner     1227000
4         Ford       Manual    Diesel    23480.0  1st owner      887000
...        ...          ...       ...        ...        ...         ...
2801      Ford    Automatic    Petrol    46982.0  1st owner      661000
2802     Honda       Manual    Petrol    38706.0  2nd owner      412000
2803   Hyundai       Manual    Petrol    31405.0  1st owner      496000
2804    Maruti       Manual    Petrol    47676.0  1st owner      509000
2805       NaN          NaN       NaN        NaN        NaN  1883558000

[2806 rows x 6 columns]

In [6]:
data = data.dropna()

In [7]:
data

brand transmission fuel_type  km_driven  ownership    price
0     Mahindra       Manual    Diesel    11003.0  1st owner  1231000
1      Hyundai       Manual    Petrol    66936.0  1st owner   786000
2         Tata       Manual    Diesel    27990.0  1st owner  1489000
3        Honda    Automatic    Petrol     5061.0  1st owner  1227000
4         Ford       Manual    Diesel    23480.0  1st owner   887000
...        ...          ...       ...        ...        ...      ...
2800     Honda       Manual    Petrol    96363.0  2nd owner   213000
2801      Ford    Automatic    Petrol    46982.0  1st owner   661000
2802     Honda       Manual    Petrol    38706.0  2nd owner   412000
2803   Hyundai       Manual    Petrol    31405.0  1st owner   496000
2804    Maruti       Manual    Petrol    47676.0  1st owner   509000

[2805 rows x 6 columns]

In [8]:
data.isnull().sum()

brand           0
transmission    0
fuel_type       0
km_driven       0
ownership       0
price           0
dtype: int64

In [9]:
data['brand'].value_counts()

brand
Maruti        925
Hyundai       660
Honda         276
Tata          240
Renault       167
KIA           116
Mahindra      114
Ford           64
Volkswagen     53
Nissan         38
MG             37
Toyota         36
Datsun         34
Skoda          33
Jeep           12
Name: count, dtype: int64

In [10]:
data['brand'].nunique()

15

In [11]:
data['ownership'].value_counts()

ownership
1st owner    2045
2nd owner     712
3rd owner      48
Name: count, dtype: int64

# 1. One hot encoding using Pandas

In [12]:
pd.get_dummies(data,columns=['fuel_type','ownership'], dtype=int)

brand transmission  km_driven    price  fuel_type_CNG  \
0     Mahindra       Manual    11003.0  1231000              0   
1      Hyundai       Manual    66936.0   786000              0   
2         Tata       Manual    27990.0  1489000              0   
3        Honda    Automatic     5061.0  1227000              0   
4         Ford       Manual    23480.0   887000              0   
...        ...          ...        ...      ...            ...   
2800     Honda       Manual    96363.0   213000              0   
2801      Ford    Automatic    46982.0   661000              0   
2802     Honda       Manual    38706.0   412000              0   
2803   Hyundai       Manual    31405.0   496000              0   
2804    Maruti       Manual    47676.0   509000              0   

      fuel_type_Diesel  fuel_type_Electric  fuel_type_Petrol  \
0                    1                   0                 0   
1                    0                   0                 1   
2                    1                   0                 0   
3                    0                   0                 1   
4                    1                   0                 0   
...                ...                 ...               ...   
2800                 0                   0                 1   
2801                 0                   0                 1   
2802                 0                   0                 1   
2803                 0                   0                 1   
2804                 0                   0                 1   

      ownership_1st owner  ownership_2nd owner  ownership_3rd owner  
0                       1                    0                    0  
1                       1                    0                    0  
2                       1                    0                    0  
3                       1                    0                    0  
4                       1                    0                    0  
...                   ...                  ...                  ...  
2800                    0                    1                    0  
2801                    1                    0                    0  
2802                    0                    1                    0  
2803                    1                    0                    0  
2804                    1                    0                    0  

[2805 rows x 11 columns]

## drop first columns!

In [13]:
pd.get_dummies(data,columns=['fuel_type','ownership'], dtype=int, drop_first=True)

brand transmission  km_driven    price  fuel_type_Diesel  \
0     Mahindra       Manual    11003.0  1231000                 1   
1      Hyundai       Manual    66936.0   786000                 0   
2         Tata       Manual    27990.0  1489000                 1   
3        Honda    Automatic     5061.0  1227000                 0   
4         Ford       Manual    23480.0   887000                 1   
...        ...          ...        ...      ...               ...   
2800     Honda       Manual    96363.0   213000                 0   
2801      Ford    Automatic    46982.0   661000                 0   
2802     Honda       Manual    38706.0   412000                 0   
2803   Hyundai       Manual    31405.0   496000                 0   
2804    Maruti       Manual    47676.0   509000                 0   

      fuel_type_Electric  fuel_type_Petrol  ownership_2nd owner  \
0                      0                 0                    0   
1                      0                 1                    0   
2                      0                 0                    0   
3                      0                 1                    0   
4                      0                 0                    0   
...                  ...               ...                  ...   
2800                   0                 1                    1   
2801                   0                 1                    0   
2802                   0                 1                    1   
2803                   0                 1                    0   
2804                   0                 1                    0   

      ownership_3rd owner  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
...                   ...  
2800                    0  
2801                    0  
2802                    0  
2803                    0  
2804                    0  

[2805 rows x 9 columns]

# One hot encoder using scikit learn
** We also use one hot encoder with the help of scikit learn always in machine learning because it learn all the parameters but pandas does not. **

In [14]:
data

brand transmission fuel_type  km_driven  ownership    price
0     Mahindra       Manual    Diesel    11003.0  1st owner  1231000
1      Hyundai       Manual    Petrol    66936.0  1st owner   786000
2         Tata       Manual    Diesel    27990.0  1st owner  1489000
3        Honda    Automatic    Petrol     5061.0  1st owner  1227000
4         Ford       Manual    Diesel    23480.0  1st owner   887000
...        ...          ...       ...        ...        ...      ...
2800     Honda       Manual    Petrol    96363.0  2nd owner   213000
2801      Ford    Automatic    Petrol    46982.0  1st owner   661000
2802     Honda       Manual    Petrol    38706.0  2nd owner   412000
2803   Hyundai       Manual    Petrol    31405.0  1st owner   496000
2804    Maruti       Manual    Petrol    47676.0  1st owner   509000

[2805 rows x 6 columns]

In [15]:
data['brand'].nunique()

15

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data.iloc[:,:5],data.iloc[:,-1],test_size=0.2,random_state=1)

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=int)

In [19]:
X_train_encoded = ohe.fit_transform(X_train[['transmission','fuel_type','ownership',]])

In [20]:
X_train_encoded

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [21]:
X_train_encoded.shape

(2244, 6)

In [22]:
X_test_encoded = ohe.transform(X_train[['transmission','fuel_type','ownership',]])

In [23]:
X_test_encoded

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [24]:
X_test_encoded.shape

(2244, 6)

In [33]:
X_train[['km_driven','brand']].values

array([[43799.0, 'Honda'],
       [11344.0, 'Maruti'],
       [14518.0, 'Tata'],
       ...,
       [93813.0, 'Maruti'],
       [24009.0, 'KIA'],
       [41750.0, 'Honda']], dtype=object)

In [35]:
np.hstack((X_train[['km_driven','brand']].values,X_train_encoded))

array([[43799.0, 'Honda', 1, ..., 1, 0, 0],
       [11344.0, 'Maruti', 1, ..., 1, 0, 0],
       [14518.0, 'Tata', 1, ..., 1, 0, 0],
       ...,
       [93813.0, 'Maruti', 1, ..., 1, 0, 0],
       [24009.0, 'KIA', 0, ..., 1, 0, 0],
       [41750.0, 'Honda', 0, ..., 1, 0, 0]], dtype=object)

# One Hot encoding with Top categories

In [38]:
counts = data['brand'].value_counts()

In [39]:
counts

brand
Maruti        925
Hyundai       660
Honda         276
Tata          240
Renault       167
KIA           116
Mahindra      114
Ford           64
Volkswagen     53
Nissan         38
MG             37
Toyota         36
Datsun         34
Skoda          33
Jeep           12
Name: count, dtype: int64

In [43]:
data['brand'].unique()
threshold = 50

In [48]:
rpl = counts[counts <= threshold].index

In [53]:
pd.get_dummies(data['brand'].replace(rpl,'uncommon'),dtype=int).sample(5)

Ford  Honda  Hyundai  KIA  Mahindra  Maruti  Renault  Tata  Volkswagen  \
1580     0      1        0    0         0       0        0     0           0   
459      0      1        0    0         0       0        0     0           0   
820      0      1        0    0         0       0        0     0           0   
2061     0      0        0    0         0       0        0     0           0   
2349     0      0        0    0         0       1        0     0           0   

      uncommon  
1580         0  
459          0  
820          0  
2061         1  
2349         0